#!/usr/bin/env python
"""
Calculate real data histogram from GroundTruth simulation h5 file.

This script reads the h5 file generated by GroundTruth simulation and computes
histogram statistics for lon_accel, lat_accel, jerk, and velocity.

Usage:
    python scripts/calculate_real_histogram.py --h5_path /path/to/gt_simulation.h5 [--mode tbsim]

Output:
    Saves hist_stats.json in the same directory as the h5 file
"""

import argparse
import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from tbsim.utils.stats_utils import compute_and_save_stats


def main():
    parser = argparse.ArgumentParser(description="Calculate real data histogram from GroundTruth h5 file")
    parser.add_argument(
        "--h5_path",
        type=str,
        required=True,
        help="Path to the h5 file generated by GroundTruth simulation"
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="groundtruth",
        choices=["tbsim", "trajdata", "groundtruth"],
        help="Mode for computing statistics. Use 'groundtruth' for GT simulation data (default: groundtruth)"
    )
    parser.add_argument(
        "--scene_keys",
        type=str,
        nargs="*",
        default=[],
        help="Optional: list of specific scene keys to process (default: all scenes)"
    )

    args = parser.parse_args()

    # Check if h5 file exists
    if not os.path.exists(args.h5_path):
        print(f"Error: h5 file not found: {args.h5_path}")
        sys.exit(1)

    print("=" * 80)
    print("Computing Real Data Histogram from GroundTruth Simulation")
    print("=" * 80)
    print(f"H5 file: {args.h5_path}")
    print(f"Mode: {args.mode}")
    if args.scene_keys:
        print(f"Processing {len(args.scene_keys)} specific scenes")
    else:
        print("Processing all scenes in h5 file")
    print("=" * 80)

    # Compute and save statistics
    compute_and_save_stats(
        h5_path=args.h5_path,
        mode=args.mode,
        scene_keys_list=args.scene_keys
    )

    # Print output location
    results_path = Path(args.h5_path).parent.resolve()
    output_file = os.path.join(results_path, "hist_stats.json")

    print("=" * 80)
    print(f"✅ Histogram statistics saved to: {output_file}")
    print("=" * 80)
    print("\nYou can now use this file with RealismDeviationMetrics:")
    print(f"  realism_deviation=EnvMetrics.RealismDeviationMetrics(")
    print(f"      real_histogram_file=\"{output_file}\"")
    print(f"  )")
    print("=" * 80)


if __name__ == "__main__":
    main()
